INSERT INTO `testlndmrk`.`user`
(`id`,
`email`,
`password`)
VALUES
(1,
'testuser@styli.com',
'test');
INSERT INTO `testlndmrk`.`customer`
(`customer_id`,
`address`,
`customer_name`,
`email`,
`gender`,
`phone_no`)
VALUES
(1,
'Address1',
'Customer1',
'testcustomer1@styli.com',
'Male',
'+912345678990');
INSERT INTO `testlndmrk`.`customer`
(`customer_id`,
`address`,
`customer_name`,
`email`,
`gender`,
`phone_no`)
VALUES
(2,
'Address2',
'Customer2',
'testcustomer2@styli.com',
'Male',
'+713445678990');
INSERT INTO `testlndmrk`.`customer`
(`customer_id`,
`address`,
`customer_name`,
`email`,
`gender`,
`phone_no`)
VALUES
(3,
'Address3',
'Customer3',
'testcustomer3@styli.com',
'Female',
'+45945678990');
INSERT INTO `testlndmrk`.`customer`
(`customer_id`,
`address`,
`customer_name`,
`email`,
`gender`,
`phone_no`)
VALUES
(4,
'Address4',
'Customer4',
'testcustomer4@styli.com',
'Male',
'+216745678990');
INSERT INTO `testlndmrk`.`customer`
(`customer_id`,
`address`,
`customer_name`,
`email`,
`gender`,
`phone_no`)
VALUES
(5,
'Address5',
'Customer5',
'testcustomer5@styli.com',
'Female',
'+6794545678990');